In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.datasets import cifar10

In [3]:
(X_train,y_train),(X_test,y_test)=cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [4]:
X_train.shape

(50000, 32, 32, 3)

In [6]:
X_test.shape

(10000, 32, 32, 3)

In [7]:
X_train=X_train/255.0
X_test=X_test/255.0

In [12]:
model=tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32,32,3)),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax'),
])

In [16]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [18]:
history=model.fit(X_train,y_train,epochs=5,batch_size=64)

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - accuracy: 0.3258 - loss: 1.8811
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.3985 - loss: 1.6903
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.4299 - loss: 1.5994
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.4472 - loss: 1.5550
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 15ms/step - accuracy: 0.4599 - loss: 1.5153


In [28]:
loss,accuracy=model.evaluate(X_test,y_test)
loss

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4552 - loss: 1.5135


1.5134589672088623

In [29]:
accuracy

0.4551999866962433

In [21]:
model.predict(X_test)[0]

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([0.03512378, 0.0923058 , 0.06754209, 0.3360865 , 0.04606953,
       0.22923605, 0.07109129, 0.00412167, 0.11169861, 0.00672463],
      dtype=float32)

In [23]:
y_test[0]

array([3], dtype=uint8)

In [24]:
model.predict(X_test)[1]

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([4.9365401e-02, 2.8895983e-01, 1.1737610e-03, 1.1886607e-03,
       6.4195518e-04, 7.6287519e-04, 1.2559292e-04, 8.1260712e-04,
       6.8626791e-02, 5.8834255e-01], dtype=float32)

In [26]:
y_test[1]

array([8], dtype=uint8)